add functionality for working with tasks
ushachev/taskmanager-dualboot pull request #17
Opened 2022-12-02 10:47 UTC by ushachev

2022-12-12 07:23 UTC, greybutton requested changes
странное смешение async/await и промисов. по идее, надо что то одно выбрать

2022-12-12 07:23 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +import TaskForm from '../../forms/TaskForm';
from 'forms/TaskForm';

2022-12-12 07:23 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import Task from '../Task';
from 'components/Task';

2022-12-12 07:23 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import useStyles from './useStyles.js';
это в самом конце импортируем

2022-12-12 07:23 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      if (transition) {
лучше guard expression сделать

2022-12-12 07:23 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +import FetchHelper from '../utils/fetchHelper';
from 'utils/

2022-12-12 07:23 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +    return axios.post(url, { task: body }).then(camelize);
этот фетчер подразумевался как универсальный, не только с тасками работать, а с любыми запросами

2022-12-12 07:23 UTC, greybutton commented on package.json
> +    "ramda": "^0.28.0",
не хватает qs пакета

2022-12-15 19:03 UTC, ushachev commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      if (transition) {
пришлось отказаться от guard expression. Eslint ругался по этому правилу [consistent-return](https://eslint.org/docs/latest/rules/consistent-return). Если в середине функции что-то возвращается, то и в конце - тоже. Причём `return undefined` не подходит, а возвращать что-либо из хэндлера семантически неверно. К тому же после подключения Redux, здесь осталась одна строчка в `if`

2022-12-19 07:28 UTC, greybutton requested changes
> [Merge branch 'develop' into feature/tasks](https://github.com/ushachev/taskmanager-dualboot/pull/17/commits/90b8366ad82ecf92f0f2339e4aecbfa1bcd68d7d)

таких коммитов быть не должно, если нужно из девелопа код в ветке, то ребейз ветки от девелопа делаем

2022-12-19 07:28 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      if (transition) {
почему на async/await вместе try/catch переписал? у нас же промисы были. В EditPopup и AddPopup еще один вариант написания запросов. Лучше конечно что то одно выбрать в проекте

2022-12-19 07:28 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  const setColumnCards = async (state) => {
именованние не очень удачное, set значит что мы ставим/обновляем что то, а внутри делается запрос + обновление. Именование скрыло факт запроса, а это важно знать при использовании функции. set не подразумевает запрос

2022-12-19 07:28 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        renderColumnHeader={(column) => <ColumnHeader column={column} onLoadMore={updateColumnCards} />}
здесь тоже именованние не очевидное onLoadMore={updateColumnCards}

2022-12-20 12:20 UTC, ushachev commented
> > [Merge branch 'develop' into feature/tasks](https://github.com/ushachev/taskmanager-dualboot/pull/17/commits/90b8366ad82ecf92f0f2339e4aecbfa1bcd68d7d)
> 
> таких коммитов быть не должно, если нужно из девелопа код в ветке, то ребейз ветки от девелопа делаем

я этот коммит сам не делал. Гитхаб под PR написал о конфликте в одном файле`package.json` и предложил его разрешить. По итогу правки во встроенном редакторе и создался этот коммит.
А можно ли было ребейз ветки делать, ведь она уже была опубликована и были коменты к коммитам? Конфликт возник позже, когда ветка девелоп ушла вперёд уже после создания этого PR.
Ребейз, я так понимаю, и теперь не поздно сделать, но коммиты же пересоздадутся. Может PR закрыть и новый создать? Или стягивать этот мерж-коммит и делать ребейз?

2022-12-20 12:23 UTC, ushachev commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  const setColumnCards = async (state) => {
эта функция - сервисная обёртка над двумя инструкциями чтобы не писать одинаковый код в нескольких местах. Содержит один запрос, одну команду. Если вынести в название не команду, а запрос, как предложено - `loadColumnInitial`, то оно будет вызывать больше удивления - что-то загружаем, ничего не возвращаем, ещё и стейт меняем. Я вижу как без неё обойтись. Мне бы вот этот [комментарий](https://github.com/ushachev/taskmanager-dualboot/pull/17#issuecomment-1359279068)  разрулить и исправлю

2022-12-20 12:25 UTC, ushachev commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      if (transition) {
я и выбрал. [Вот и попапы исправлены](https://github.com/ushachev/taskmanager-dualboot/pull/17/commits/709e54271136c6983837a7150538a02976d243c6). С async/await код плоский, естественный, читается сверху вниз, без ответвлений вбок. Без лишних скобок и в большинстве случаев компактнее, несмотря на try/catch, который и не всегда нужен.
```
await doSmthAsync();
doSmth2();
doSmth3();
```
вместо
```
doSmthAsync().then(() => {
  doSmth2();
  doSmth3();
});
```
конечно `loadCard(cardId).then(setTask)` компактнее некуда, но если надо выбрать что-то одно, то по мне async/await лучше в большинстве случаев

2023-01-30 07:39 UTC, greybutton approved these changes

2023-01-30 09:00 UTC, merged